image: "electronuserland/builder:wine"

before_script:
  - mkdir -p electron
  - mkdir -p electron-builder
  - mkdir -p $HOME/.cache
  - cp -R electron $HOME/.cache/electron
  - cp -R electron-builder $HOME/.cache/electron-builder

stages:
  - build

build:
  dependencies: []
  stage: build
  artifacts:
    paths:
    - dist/*.*
    expire_in: 1 day
  cache:
    key: build
    paths:
      - node_modules/
      - electron/
      - electron-builder/
  script:
    - rm -rf electron-builder
    - rm -rf electron
    - npm ci && npm run-script build-win && npm run-script build-linux
    - cp -R $HOME/.cache/electron electron
    - cp -R $HOME/.cache/electron-builder electron-builder
